name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  PCLOUD_HOST: ${{ secrets.PCLOUD_HOST }}
  PCLOUD_PASSWORD: ${{ secrets.PCLOUD_PASSWORD }}
  PCLOUD_USER: ${{ secrets.PCLOUD_USER }}
  RUST_LOG: debug
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
